# Generated by Django 2.2.28 on 2025-06-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('hashed', models.CharField(blank=True, editable=False, max_length=20, null=True)),
            ],
            options={
                'db_table': 'shop_shop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShopImage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='shop_images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('is_banner', models.BooleanField(default=False)),
                ('size', models.CharField(blank=True, choices=[('1x1M', '1x1 M'), ('2x1M', '2x1 M'), ('3x1M', '3x1 M'), ('4x1M', '4x1 M')], max_length=20, null=True)),
                ('hashed', models.CharField(blank=True, editable=False, max_length=20, null=True)),
            ],
            options={
                'db_table': 'shop_shopimage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserShop',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'shop_usershop',
                'managed': False,
            },
        ),
    ]
