# Generated by Django 2.2.28 on 2025-06-23 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='shopimage',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usershop',
            options={'managed': True},
        ),
    ]
