# Generated by Django 2.2.28 on 2025-06-25 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom', '0003_auto_20250625_1721'),
        ('shop', '0002_auto_20250623_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='administrativepost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AdministrativePost', to='custom.AdministrativePost'),
        ),
        migrations.AddField(
            model_name='shop',
            name='aldeia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Aldeia', to='custom.Aldeia'),
        ),
        migrations.AddField(
            model_name='shop',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='center', to='custom.Municipality'),
        ),
        migrations.AddField(
            model_name='shop',
            name='kind_of_channel',
            field=models.ManyToManyField(blank=True, related_name='shops', to='custom.Channel'),
        ),
        migrations.AddField(
            model_name='shop',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Municipality', to='custom.Municipality'),
        ),
        migrations.AddField(
            model_name='shop',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Village', to='custom.Village'),
        ),
        migrations.AddField(
            model_name='shopimage',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_images', to='shop.Shop'),
        ),
        migrations.AddField(
            model_name='usershop',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Shop'),
        ),
        migrations.AddField(
            model_name='usershop',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ShopOwner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shop',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='shopimage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usershop',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
