# Generated by Django 2.2.2 on 2025-07-08 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20250625_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='deploy_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='dimension',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='kind_of_banner',
            field=models.CharField(blank=True, choices=[('Big banner with frame', 'Big banner with frame'), ('Small Banner', '\uf0a7\tSmall Banner')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='update_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
