# Generated by Django 2.2.2 on 2025-07-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20250708_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='deploy_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
