# Generated by Django 2.2.2 on 2025-07-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20250708_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopimage',
            name='is_banner',
        ),
        migrations.RemoveField(
            model_name='shopimage',
            name='is_primary',
        ),
        migrations.RemoveField(
            model_name='shopimage',
            name='size',
        ),
        migrations.AddField(
            model_name='shopimage',
            name='is_id',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shop',
            name='kind_of_banner',
            field=models.CharField(blank=True, choices=[('Big banner with frame', 'Big banner with frame'), ('Small Banner', 'Small Banner')], max_length=100, null=True),
        ),
    ]
