# Generated by Django 2.2.2 on 2025-07-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20250709_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopimage',
            name='is_id',
        ),
        migrations.AddField(
            model_name='shopimage',
            name='image_type',
            field=models.CharField(choices=[('ID', 'ID'), ('FIX', 'FIX'), ('UPDATE', 'UPDATE')], default='OTHER', max_length=50),
        ),
        migrations.AddField(
            model_name='shopimage',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
