# Generated by Django 2.2.28 on 2025-06-23 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrativepost',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='aldeia',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='channel',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='municipality',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='village',
            options={'managed': True},
        ),
    ]
